
- name: invenio
  hosts: sceiba-invenio
  remote_user: root
  roles:
  - role: invenio
    vars:
      git_repo: "https://github.com/tocororo/iroko.git"
      IP_ELASTIC : "10.2.4.62"
      IP_POSGRE : "10.2.4.29"
      IP_RABBIT : "10.2.4.59"
      IP_REDIS : "10.2.4.58"

      APP_ALLOWED_HOSTS :
        - 'sceiba-lab.upr.edu.cu'
        - 'localhost'
        - '127.0.0.1'
        - '10.2.4.49'
        - '200.14.49.24'
      IROKO_HOST: 'https://sceiba-lab.upr.edu.cu'
      invenio_buildall: true
      invenio_collect: true
      invenio_requirements: true
      invenio_self_install: true
      IROKO_ORCID_consumer_key: "APP-XXXXXXXXXXXX"
      IROKO_ORCID_consumer_secret: "secret"
      IROKO_EXTRA_lines:
        - "import os"
        # - "os.environ['http_proxy'] = 'http://servers-proxy.upr.edu.cu:8080/'"
        # - "os.environ['https_proxy'] = 'http://servers-proxy.upr.edu.cu:8080/'"
        # - "os.environ['no_proxy'] = '10.2.0.0/15'"
        - "INIT_STATIC_JSON_PATH = '/mnt/data/texts'"
        - "HARVESTER_DATA_DIRECTORY ='/data/sceiba-data'"
        - "INIT_TAXONOMY_JSON_PATH = '/data/taxonomy.json'"
        - "INIT_JOURNALS_JSON_PATH = '/data/journals.json'"
        - "INIT_OAIURL_JSON_PATH = '/data/oaisources.json'"
        - "IROKO_TEMP_DIRECTORY = '/tmp'"
        - "IROKO_DATA_DIRECTORY = 'data'"
        - "HARVESTER_SECONDARY_DIRECTORY = '/data/2_harvest_data'"
        - "REST_ENABLE_CORS = True"

  environment:
    LC_ALL: C.UTF-8

